master:
  hosts:
    k3s-master-a:
      ansible_host: "k3s-master-a.mdbraber.net"
  vars:
    k3s_control_node: true
    k3s_tls_san: "k3s.mdbraber.net"

nodes:
  hosts:
    k3s-worker-a:
      ansible_host: "k3s-worker-a.mdbraber.net"
    k3s-worker-b:
      ansible_host: "k3s-worker-b.mdbraber.net"
  vars:

nfs:
  hosts:

ceph:
  hosts:
    k3s-worker-a:
    k3s-worker-b:
  vars:

k3s_cluster:
  children:
    master:
    nodes:

storage:
  children:
    ceph:

vault:
  hosts:
    localhost:
      ansible_connection: local
